name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write   

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@master
        with:
          github_user_name: Danish137
          svg_out_path: github-snake.svg
          outputs: |
            github-snake.svg
          color_snake: "#22c55e"
          color_dots: "#0f172a"
          color_dots_empty: "#020617"

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-snake.svg
          git commit -m "Update snake" || echo "No changes"
          git push
